#!/bin/env python3

def genDefList(idarr):
    s = '#if'
    cter = 1
    for i in idarr:
        s += ' defined(' + i + ')'
        if cter != len(idarr):
            s += ' ||'
        cter += 1
    return s

print('// Generated by cc_codegen.py. Do not edit it by hand.')

with open("cc_list") as fd:
    osarr=fd.read().split('\n')
    for i in osarr:
        if i == '':
            continue
        iarr=i.split(' ')
        if len(iarr) < 2:
            continue
        print('#ifndef __COMPILER_ID__')
        print(genDefList(iarr[:-1:]))
        print('#define __COMPILER_ID__', iarr[-1])
        print('#endif')
        print('#endif')
        print('')

print('#ifndef __COMPILER_ID__')
print('#define __COMPILER_ID__ UNKNOWN')
print('#endif')

